export const ProjectList = [
  {
    id: 1,
    image: '/project-1.webp',
    title: 'New Vision Education Center',
    projectURL: 'https://nvec-lms.vercel.app/',
    desc: 'The Learning Management System (LMS) project is a web-based platform designed to facilitate online learning and training.',
    stacks: [
      { id: 1, name: 'Next.js' },
      { id: 2, name: 'Tailwind Css' },
      { id: 3, name: 'Zustand' },
      { id: 4, name: 'React Query' },
      { id: 5, name: 'Nest.js' },
      { id: 6, name: 'MySQL' },
    ],
  },
  {
    id: 2,
    title: 'BitBazaar',
    image: '/project-2.webp',
    projectURL: 'https://bitbazaar.vercel.app/',
    githubURL: 'https://github.com/myatminag/BitBazaar',
    desc: 'Game store is designed to evolutionize the gaming industry by providing a seamless and immersive shopping experience for gamers.',
    stacks: [
      { id: 1, name: 'Next.js' },
      { id: 2, name: 'Tailwind Css' },
      { id: 3, name: 'React Query' },
      { id: 4, name: 'Rawg.io API' },
    ],
  },
  {
    id: 3,
    title: 'Empress',
    image: '/project-3.webp',
    projectURL: 'https://empress.vercel.app/',
    githubURL: 'https://github.com/myatminag/Empress',
    desc: 'The eCommerce platform caters to a diverse range of products, offering users a visually appealing interface combined with advanced functionality.',
    stacks: [
      { id: 1, name: 'React.js' },
      { id: 2, name: 'Tailwind Css' },
      { id: 3, name: 'React Router' },
      { id: 4, name: 'React Query' },
      { id: 5, name: 'Express.js' },
      { id: 6, name: 'Mongodb' },
    ],
  },
  {
    id: 4,
    title: 'Journeys',
    image: '/project-4.webp',
    projectURL: 'https://journeyss.vercel.app/',
    githubURL: 'https://github.com/myatminag/TheJourney',
    desc: 'A dynamic and engaging blog platform aimed at providing a captivating space for content creation and consumption.',
    stacks: [
      { id: 1, name: 'React.js' },
      { id: 2, name: 'Tailwind Css' },
      { id: 3, name: 'React Router' },
      { id: 4, name: 'React Query' },
      { id: 5, name: 'Express.js' },
      { id: 6, name: 'Mongodb' },
    ],
  },
];
